### ISSUE TITLE
QtWidgets.QApplication.clipboard() issues

### ISSUE THREAD

**Issue by sertraline** [sertraline/chizuhoru#1]
PyQt has its own clipboard that one can access through QtWidgets.QApplication.clipboard(), so it can be used to save images directly from memory instead of saving them to disk and then using xclip:
```python
Chizuhoru > processing.py > convert(args, app, kwargs)

        # image has type of a PIL .PNG image
        pre_img = ImageQt(image)
        # ImageQt is a PIL module to convert images to Qt format
        qim = QImage(pre_img)
        pixmap = QPixmap(qim)
        app.clipboard().clear(mode=app.clipboard().Clipboard)
        app.clipboard().setPixmap(pixmap)
```
Most of the time it works but also breaks dbus for whatever reason when I try to init notify2; there is notable freeze in KDE for a few seconds while dbus is stuck waiting for notification to appear. Notification will either appear or crash the whole script:
<details>
  <summary>DBus trace</summary>

```
ERROR:dbus.proxies:Introspect error on :1.19:/org/freedesktop/Notifications: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ERROR:dbus.connection:Unable to set arguments ('Chizuhoru', 0, '', 'Cheese!', 'Image was copied to the clipboard.', [], {}, -1) according to signature None: <class 'ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "Chizuhoru/main.py", line 139, in keyPressEvent
    n.show()
  File "/usr/lib/python3.7/site-packages/notify2.py", line 229, in show
    self.timeout,  # expire_timeout
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
```
</details>  

There is high chance to get visual artifacts on the image:
![artifact1](https://i.imgur.com/i3jz7a1.png)  

![artifact2](https://i.imgur.com/xDOt79W.png)

Some chance of getting segfault as well:
```
python3 Chizuhoru/main.py                
[1]    5339 segmentation fault (core dumped)  python3 Chizuhoru/main.py
```  
  
May be related to compositor issues which in my case is KWin working with nouveau drivers. Have no idea can I fix it and how to fix it, so for now I'll stick with xclip.

**Comment by sertraline** [comment]
Segfaults and skewings were coming from PIL.ImageQt convert function.  Now issue is fixed by creating a virtual file object (io.BytesIO) and saving the picture to it. QImage does not accept bytes, but you can load them into it by using `QImage.loadFromData(bytes.getvalue())`. Then I had to create QMimeData object in order to have a proper pointer to the memory.
